### PR TITLE
setup exclusion list

### LINKED ISSUE #32: emacs temp file causes a crash
## Background
- I use [spacemacs](https://github.com/syl20bnr/spacemacs) for tending my garden
  - It creates an autosave file for anything you are currently editing, like
    `garden/.#empathizing-with-your-users.mdx`
  - This file is added and then removed 
  - I don't completely understand how this happens, and whether it's a configurable feature or not 😅

## Problem
- When I change a file in my content directory, my gatsby build breaks and I get the following error
  ```
  Error: ENOENT: no such file or directory, open 'garden/.#empathizing-with-your-users.mdx'

  - get-markdown-notes.js:23
    [personal-blog]/[@aengusm]/gatsby-theme-brain/src/get-markdown-notes.js:23:24

  - Array.map

  - get-markdown-notes.js:17 module.exports
    [personal-blog]/[@aengusm]/gatsby-theme-brain/src/get-markdown-notes.js:17:6
  ```

### PR DESCRIPTION
**Pull request by JuanCaicedo**
Fixes #32

## What 
- Adds exclusion option to the plugin
- Files matching exclusions are not included in the build when getting notes
- Exclusions can be strings or regexps

## How to test
- Set up a gatsby project using this project
- Add 3 notes to your content directory (`note-a.mdx`, `note-b.mdx`, `note-c.mdx`)
- Add `exclude: [/^note-b/, 'note-c.mdx']` to your plugin options
- When you run the build, a page should be generated only for `note-a.mdx`

### CODE REVIEW

File: src/get-markdown-notes.js [hunk 1]
```diff
@@ -1,27 +1,42 @@
...
+  !regExps.some(matches(filename));
+
 module.exports = (pluginOptions) => {
   let notesDirectory = pluginOptions.notesDirectory || "content/brain/";
   let notesFileExtensions = pluginOptions.notesFileExtensions || [
     ".md",
     ".mdx",
   ];
+  let exclusions =
+    (pluginOptions.exclude && pluginOptions.exclude.map(toRegExp)) || [];
```
Comment (JuanCaicedo) [inline src/get-markdown-notes.js:22]: My reasoning for mapping all the contents of `exclude` to regexps here is that then we can keep that logic separate from the filtering logic later

File: src/get-markdown-notes.js [hunk 2]
```diff
@@ -1,27 +1,42 @@
...
 const path = require("path");
 
+function toRegExp(value) {
+  if (typeof value === "string") {
+    return new RegExp(`^${value}$`);
+  }
+  return value;
+}
+
+const matches = (filename) => (regExp) => regExp.test(filename);
```
Comment (JuanCaicedo) [inline src/get-markdown-notes.js:11]: `.test()` seems like the best thing to leverage here. Unfortunately it can only be called from `RegExp`s, so that's why we convert all strings to regexps

File: src/get-markdown-notes.js [hunk 3]
```diff
@@ -1,27 +1,42 @@
 const fs = require("fs");
 const path = require("path");
 
+function toRegExp(value) {
+  if (typeof value === "string") {
+    return new RegExp(`^${value}$`);
+  }
+  return value;
+}
```
Comment (JuanCaicedo) [inline src/get-markdown-notes.js:9]: This is pretty naive, only strings will get turned to `RegExps`, anything else is not changed. That means that if someone passes a value other than a `RegExp` or `String` to the `exclude` option, the build will fail. 

I figure if that becomes a concern, the best way to handle it would be to have a validation step for these arguments earlier in the library, rather than handling them at this low level 😀

Comment (aengusmcmillin) [reply src/get-markdown-notes.js:9]: This seems fine for now. Yeah there is very little validation right now in general, and that may be something to work on, but this shouldn't be a big deal yet

**Comment by aengusmcmillin** [comment]
Cool, thanks for this! Seems like a reasonable fix and a good extension to make the plugin a little more versatile
